### ISSUE TITLE
Error when seeding

### ISSUE THREAD

**Issue by Frexuz** [veeqo/activejob-uniqueness#49]
```
class Notification < ApplicationRecord
  ...
  after_create_commit :after_create

  def after_create
    case notification_type
    when 'incoming_friend_request'
      ::BroadcastIncomingFriendRequestNotificationJob.set(wait: 1.seconds).perform_later(self)
    when 'accepted_friend_request'
      ...
    end
  end
end
```
```
class BroadcastIncomingFriendRequestNotificationJob < ActiveJob::Base
  unique :until_executed

  def perform(notification)
    if notification.unread?(notification.notificationable)
      notification.broadcast
    end
  end
end
```
```
-------------------------------------------------------------
Seeding!
-------------------------------------------------------------
rails aborted!
ActiveJob::Uniqueness::JobNotUnique: Not unique BroadcastIncomingFriendRequestNotificationJob (Job ID: a62bc78e-e835-4578-b5a9-3c152c269308) (Lock key: activejob_uniqueness:broadcast_incoming_friend_request_notification_job:0e593936c1e000761d743910639b1be4) [#<Notification id: 1, user_id: 2, notification_type: "incoming_friend_request", actor_type: "User", actor_id: 1, notificationable_type: "User", notificationable_id: 1, created_at: "2022-08-12 14:17:59.782068000 +0000", updated_at: "2022-08-12 14:17:59.782068000 +0000">]
/Users/frexuz/www/travclub-api/app/models/notification.rb:41:in `after_create'
/Users/frexuz/www/travclub-api/app/models/friendship.rb:61:in `notify_incoming_friend_request'
/Users/frexuz/www/travclub-api/lib/tasks/seeds/seed_friends.rake:8:in `block (2 levels) in <main>'
/Users/frexuz/www/travclub-api/db/seeds.rb:8:in `<main>'
```

Any idea? (this is in development)

I thought `perform_later(self)` would create a unique job id :)

gem 'rails', '6.1.6'
gem 'sidekiq', '6.5.1'
gem 'activejob-uniqueness', '0.2.4'

**Comment by sharshenov** [comment]
Job id is unique, but the lock key depends on job arguments. If you don't need to capture lock uniqueness violations, just set `config.on_conflict = :log` [in the initializer](https://github.com/veeqo/activejob-uniqueness/blob/7a56859976e9e2c3aa3dfab088d5644bc0e23ae5/lib/generators/active_job/uniqueness/templates/config/initializers/active_job_uniqueness.rb#L20)
